[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\kelvin.obi\Documents\Codex\2026-07-04\canva-plugin-canva-openai-curated-remote\outputs\QualitrolFATSummaryInstaller-OnePagePictures.exe
FriendlyName=Qualitrol FAT Summary Installer
AppLaunched=wscript.exe LaunchInstaller.vbs
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="BootstrapInstall.ps1"
FILE1="LaunchInstaller.vbs"
FILE2="Payload.zip"
[SourceFiles]
SourceFiles0=C:\Users\kelvin.obi\Documents\Codex\2026-07-04\canva-plugin-canva-openai-curated-remote\work\fat_summary_app\native_installer\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
